%% must run the script RemoveOscillations.m first 
%  so that the relavent variables are in the workspace

RemoveOscillations.m

%% now we plot the ACF1 signal

fig1 = figure;
fig1.Units = 'centimeters';
fig1.Position = [0,15,25,31];
fig1.Resize = 'off';
fontsize = 18;
linethickness = 1.5;
meanthickness = 3.5;
hold on

pos1 = [0.1 0.76 0.87 0.22];
pos2 = pos1 - [0 0.23 0 0];
pos3 = pos2 - [0 0.22 0 0];
pos4 = pos3 - [0 0.22 0 0];

%% suplot1: time series

ax1 = subplot('Position',pos1);
hold on
plot(ax1, t, X-mean(X),...
    'Color', Rcol, 'LineWidth', 2*linethickness)
plot(ax1, t, newslp_D,...
    'Color', Dcol, 'LineWidth', linethickness)
plot(ax1, t, newslp_S,...
    'Color', Scol, 'LineWidth', linethickness)
ylabel({'SLP (hPa)'},'Interpreter','latex')
xlim(tlimits);
xticks(tticks);
ylim([-1.9,3.9]);
ann = annotation('textbox',...
    pos1 + [0.03 0 0 0],...
    'String','a',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
xticklabels([]);
legend(ax1,{'original','filtered',['sine wave']},...
    'Location','northeast','FontSize',fontsize, 'FontName', 'Times New Roman','Interpreter','latex')
set(gca,'YGrid','on','XGrid','on','XAxisLocation','top','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')

%% suplot2: ACF1

ax2 = subplot('Position',pos2);
hold on
plot(ax2, t,ACF_R,...
    'Color',Rcol,'LineWidth', 2*linethickness)
plot(ax2, t, ACF_D,...
    'Color',Dcol,'LineWidth', linethickness)
plot(ax2, t, ACF_S,...
    'Color',Scol,'LineWidth', linethickness)
ylabel({'ACF1 indicator'},'Interpreter','latex')
xlim(tlimits);
xticks(tticks);
%ylim([-2,2]);
xlabel({'time before event (hours)'},'Interpreter','latex')
yticks([0.8, 0.9]);
ann = annotation('textbox',...
    pos2 + [0.03 -0.02 0 0],...
    'String','b',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')

%% suplot3: DFA

ax3 = subplot('Position',pos3);
hold on
plot(ax3, t(windowSize:end), DFA_R,...
    'Color',Rcol,'LineWidth', 2*linethickness)
plot(ax3, t(windowSize:end), DFA_D,...
    'Color',Dcol,'LineWidth', linethickness)
plot(ax3, t(windowSize:end), DFA_S,...
    'Color',Scol,'LineWidth', linethickness)
ylabel({'DFA indicator'},'Interpreter','latex')
xlim(tlimits);
xticks(tticks);
%ylim([-2,2]);
xlabel({'time before event (hours)'},'Interpreter','latex')
yticks([1, 1.5]);
ann = annotation('textbox',...
    pos3 + [0.03 -0.02 0 0],...
    'String','c',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')


%% suplot4: PS

ax4 = subplot('Position',pos4);
hold on
plot(ax4, t,PS_R,...
    'Color',Rcol,'LineWidth', 2*linethickness)
plot(ax4, t, PS_D,...
    'Color',Dcol,'LineWidth', linethickness)
plot(ax4, t, PS_S,...
    'Color',Scol,'LineWidth', linethickness)
ylabel({'PS indicator'},'Interpreter','latex')
xlim(tlimits);
xticks(tticks);
%ylim([-2,2]);
xlabel({'time before event (hours)'},'Interpreter','latex')
yticks([-2, 0, 2]);
ann = annotation('textbox',...
    pos4 + [0.03 -0.02 0 0],...
    'String','d',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')