%% Plot_pitchforkMuRelationship.m 
%
% Plots the relationship between the pitchfork model parameter mu and
% the PS exponent, and also between mu and the ACF1.
%

%% Fetch data
% either run the script or load the workspace

% Calculate_pitchforkMuRelationship.m
load pitchforkMuRelationship_workspace.mat 

%% Nice plot
fig1 = figure; fig1.Units = 'centimeters'; fig1.Resize = 'off';
fig1.Position = [0,0,30,15];
fontsize = 18;
hold on
pos1 = [0.07 0.15 0.40 0.80];
pos2 = pos1 + [0.52 0 0 0];
xlimits = [mu_vals(1),mu_vals(end)];

ax1 = subplot('Position',pos1);
hold on
ylimits = [-0.2,2];
plot(ax1,mu_vals, ps_vals, 'Color', 'k', 'LineWidth',2,...
    'LineStyle','none','Marker','o','MarkerSize',5)
plot([0,0],ylimits, 'LineStyle','--','LineWidth',2,'Color','r')
ylim(ylimits)
xlim(xlimits)
xlabel('pitchfork model parameter \mu')
ylabel('PS exponent \beta')
ann1 = annotation('textbox',...
    pos1 + [0.02 0 0 -0],...
    'String','a',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
% annotation_string = '(PS method)';
% ann2 = annotation('textbox',...
%     pos1 + [0.05 0 0 0],...
%     'String',annotation_string,...
%     'FontSize', 20',...
%     'LineStyle', 'none',...
%     'FitBoxToText', 'off',...
%     'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','XAxisLocation','bottom',...
    'box','on','FontSize',fontsize, 'FontName', 'Times New Roman')

ax2 = subplot('Position',pos2);
hold on
ylimits = [-0.1,1];
plot(ax2,mu_vals, acf1_vals, 'Color', 'k', 'LineWidth',2,...
    'LineStyle','none','Marker','o','MarkerSize',5)
plot([0,0],ylimits, 'LineStyle','--','LineWidth',2,'Color','r')
ylim(ylimits)
xlim(xlimits)
xlabel('pitchfork model parameter \mu')
ylabel('lag-1 ACF')
ann1 = annotation('textbox',...
    pos2 + [0.02 0 0 0],...
    'String','b',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
% annotation_string = '(ACF1 method)';
% ann2 = annotation('textbox',...
%     pos2 + [0.05 0 0 0],...
%     'String',annotation_string,...
%     'FontSize', 20',...
%     'LineStyle', 'none',...
%     'FitBoxToText', 'off',...
%     'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','XAxisLocation','bottom',...
    'box','on','FontSize',fontsize, 'FontName', 'Times New Roman')

clear ann1 ann2 pos1 pos2 ax1 ax2 annotation_string
clear fontsize ylimits xlimits 