%% load data

load AlternativeEOFData

%% Plot DFA

time_axis = AlternativeEOFData.time;

fig1 = figure;
fig1.Units = 'centimeters';
fig1.Position = [0,15,25,15];
fig1.Resize = 'off';
fontsize = 18;
linethickness = 2;
hold on

pos1 = [0.1 0.60 0.87 0.30];
pos2 = pos1 - [0 0.33 0 0];

ax1 = subplot('Position',pos1)
hold on
plot(ax1, time_axis, AlternativeEOFData.mean_DFA_reg,...
    'Color','k','LineWidth', linethickness)
plot(ax1, time_axis,...
    AlternativeEOFData.mean_DFA_reg + ...
    AlternativeEOFData.std_DFA_reg,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax1, time_axis,...
    AlternativeEOFData.mean_DFA_reg - ...
    AlternativeEOFData.std_DFA_reg,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
ylabel({'DFA indicator'},'Interpreter','latex')
%xlim([]);
%ylim([-0.29,0.29]);
ann = annotation('textbox',...
    pos1 + [0.03 0 0 0],...
    'String','a',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
xticklabels([]);
set(gca,'YGrid','on','XGrid','on','XAxisLocation','top','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')



ax2 = subplot('Position',pos2)
hold on
plot(ax2, time_axis, AlternativeEOFData.mean_DFA_alt,...
    'Color','k','LineWidth', linethickness)
plot(ax2, time_axis,...
    AlternativeEOFData.mean_DFA_alt + ...
    AlternativeEOFData.std_DFA_alt,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax2, time_axis,...
    AlternativeEOFData.mean_DFA_alt - ...
    AlternativeEOFData.std_DFA_alt,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
ylabel({'DFA indicator'},'Interpreter','latex')
xlabel({'$t$'},'Interpreter','latex')
%xlim([]);
%ylim([0.88,0.98]);
ann = annotation('textbox',...
    pos2 + [0.03 -0.03 0 0],...
    'String','b',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')





%% Plot ACF1

time_axis = AlternativeEOFData.time;

fig1 = figure;
fig1.Units = 'centimeters';
fig1.Position = [0,15,25,15];
fig1.Resize = 'off';
fontsize = 18;
linethickness = 2;
hold on

pos1 = [0.1 0.6 0.87 0.30];
pos2 = pos1 - [0 0.33 0 0];

ax1 = subplot('Position',pos1)
hold on
plot(ax1, time_axis, AlternativeEOFData.mean_ACF1_reg,...
    'Color','k','LineWidth', linethickness)
plot(ax1, time_axis,...
    AlternativeEOFData.mean_ACF1_reg + ...
    AlternativeEOFData.std_ACF1_reg,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax1, time_axis,...
    AlternativeEOFData.mean_ACF1_reg - ...
    AlternativeEOFData.std_ACF1_reg,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
ylabel({'ACF1 indicator'},'Interpreter','latex')
%xlim([]);
ylim([0.89,0.96]);
ann = annotation('textbox',...
    pos1 + [0.03 0 0 0],...
    'String','a',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
xticklabels([]);
set(gca,'YGrid','on','XGrid','on','XAxisLocation','top','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')



ax2 = subplot('Position',pos2)
hold on
plot(ax2, time_axis, AlternativeEOFData.mean_ACF1_alt,...
    'Color','k','LineWidth', linethickness)
plot(ax2, time_axis,...
    AlternativeEOFData.mean_ACF1_alt + ...
    AlternativeEOFData.std_ACF1_alt,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax2, time_axis,...
    AlternativeEOFData.mean_ACF1_alt - ...
    AlternativeEOFData.std_ACF1_alt,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
ylabel({'ACF1 indicator'},'Interpreter','latex')
xlabel({'$t$'},'Interpreter','latex')
%xlim([]);
ylim([0.89,0.96]);
ann = annotation('textbox',...
    pos2 + [0.03 -0.03 0 0],...
    'String','b',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')
