%% Load data

% This data has been created using Hopf100_EM.m
load HopfData_EM

HopfData = HopfData_EM;
clear HopfData_EM
%% Plot

fig1 = figure;
fig1.Units = 'centimeters';
fig1.Position = [0,15,25,28];
fig1.Resize = 'off';
fontsize = 18;
linethickness = 2;
hold on

pos1 = [0.1 0.76 0.87 0.20];
pos2 = pos1 - [0 0.20 0 0];
pos3 = pos2 - [0 0.21 0 0];
pos4 = pos3 - [0 0.21 0 0];
%pos5 = pos4 - [0 0.18 0 0];

ax1 = subplot('Position',pos1);
hold on
plot(ax1, HopfData.time, HopfData.mean_real,...
    'Color','k','LineWidth', linethickness)
plot(ax1, HopfData.time,...
    HopfData.mean_real+HopfData.std_real,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax1, HopfData.time,...
    HopfData.mean_real-HopfData.std_real,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
ylabel({'Re$(\lambda_1)$'},'Interpreter','latex')
xlim([19.5,60]);
ylim([-3.3,0]);
ann = annotation('textbox',...
    pos1 + [0.03 0 0 0],...
    'String','a',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','XAxisLocation','top',...
    'box','on','FontSize',fontsize, 'FontName', 'Times New Roman')




ax2 = subplot('Position',pos2);
hold on
plot(ax2, HopfData.time, abs(HopfData.mean_imag),...
    'Color','k','LineWidth', linethickness)
plot(ax2, HopfData.time,...
    abs(HopfData.mean_imag)+HopfData.std_imag,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax2, HopfData.time,...
    abs(HopfData.mean_imag)-HopfData.std_imag,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
xlabel({'$t$'},'Interpreter','latex')
ylabel({'Im$(\lambda_1)$'},'Interpreter','latex')
xlim([19.5,60]);
ylim([0.1,1.9]);
xticklabels([]);
ann = annotation('textbox',...
    pos2 + [0.03 0 0 0],...
    'String','b',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')






ax3 = subplot('Position',pos3);
hold on
plot(ax3, HopfData.time, HopfData.mean_ACF1,...
    'Color','k','LineWidth', linethickness)
plot(ax3, HopfData.time,...
    HopfData.mean_ACF1+HopfData.std_ACF1,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax3, HopfData.time,...
    HopfData.mean_ACF1-HopfData.std_ACF1,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
ylabel({'ACF1'},'Interpreter','latex')
xlim([19.5,60]);
ylim([0.46, 0.94]);
xticklabels([]);
ann = annotation('textbox',...
    pos3 + [0.03 0 0 0],...
    'String','c',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')




ax4 = subplot('Position',pos4);
hold on
plot(ax4, HopfData.time, HopfData.mean_DFA,...
    'Color','k','LineWidth', linethickness)
plot(ax4, HopfData.time,...
    HopfData.mean_DFA+HopfData.std_DFA,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax4, HopfData.time,...
    HopfData.mean_DFA-HopfData.std_DFA,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
xlabel({'$t$'},'Interpreter','latex')
ylabel({'DFA'},'Interpreter','latex')
xlim([19.5,60]);
ylim([0.8,2.3]);
%xticklabels([]);
ann = annotation('textbox',...
    pos4 + [0.03 0 0 0],...
    'String','d',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')

clear ax1 ax2 ax3 ax4 pos1 pos2 pos3 pos4 fontsize linethickness ann

