%%

load('HomoclinicData')
load('HopfData')
load('vdpData')

%% Plot

fig1 = figure;
fig1.Units = 'centimeters';
fig1.Position = [0,15,25,28];
fig1.Resize = 'off';
fontsize = 18;
linethickness = 2;
hold on

pos1 = [0.1 0.75 0.87 0.23];
pos2 = pos1 - [0 0.30 0 0];
pos3 = pos2 - [0 0.30 0 0];


ax1 = subplot('Position',pos1)
hold on
plot(ax1, HomoclinicData.time, HomoclinicData.mean_PS,...
    'Color','k','LineWidth', linethickness)
plot(ax1, HomoclinicData.time,...
    HomoclinicData.mean_PS+HomoclinicData.std_PS,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax1, HomoclinicData.time,...
    HomoclinicData.mean_PS-HomoclinicData.std_PS,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
ylabel({'PS indicator'},'Interpreter','latex')
xlabel({'$t$'},'Interpreter','latex')
xlim([49,100]);
%ylim([-3.3,0]);
ann = annotation('textbox',...
    pos1 + [0.03 0 0 0],...
    'String','a',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on',...
    'box','on','FontSize',fontsize, 'FontName', 'Times New Roman')




ax2 = subplot('Position',pos2)
hold on
plot(ax2, HopfData.time, HopfData.mean_PS,...
    'Color','k','LineWidth', linethickness)
plot(ax2, HopfData.time,...
    HopfData.mean_PS+HopfData.std_PS,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax2, HopfData.time,...
    HopfData.mean_PS-HopfData.std_PS,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
xlabel({'$t$'},'Interpreter','latex')
ylabel({'PS indicator'},'Interpreter','latex')
xlim([19.5,58]);
%ylim([0.1,1.9]);
%xticklabels([]);
ann = annotation('textbox',...
    pos2 + [0.03 0 0 0],...
    'String','b',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')






ax3 = subplot('Position',pos3)
hold on
plot(ax3, vdpData.time, vdpData.mean_PS,...
    'Color','k','LineWidth', linethickness)
plot(ax3, vdpData.time,...
    vdpData.mean_PS+vdpData.std_PS,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax3, vdpData.time,...
    vdpData.mean_PS-vdpData.std_PS,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
ylabel({'PS indicator'},'Interpreter','latex')
xlabel({'$t$'},'Interpreter','latex')
xlim([95,380]);
ylim([-2, 1.5]);
%xticklabels([]);
ann = annotation('textbox',...
    pos3 + [0.03 0 0 0],...
    'String','c',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')


