%% Load data

% This data has been created using Hopf100.m
%load(vdpData)

%% Plot

fig1 = figure;
fig1.Units = 'centimeters';
fig1.Position = [0,15,25,28];
fig1.Resize = 'off';
fontsize = 18;
linethickness = 2;
hold on

pos1 = [0.1 0.76 0.87 0.20];
pos2 = pos1 - [0 0.20 0 0];
pos3 = pos2 - [0 0.21 0 0];
pos4 = pos3 - [0 0.21 0 0];
pos5 = pos4 - [0 0.18 0 0];

ax1 = subplot('Position',pos1)
hold on
plot(ax1, vdpData.time, vdpData.mean_real,...
    'Color','k','LineWidth', linethickness)
plot(ax1, vdpData.time,...
    vdpData.mean_real+vdpData.std_real,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax1, vdpData.time,...
    vdpData.mean_real-vdpData.std_real,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
ylabel({'Re$(\lambda_1)$'},'Interpreter','latex')
xlim([200,380]);
ylim([-0.19,0.01]);
ann = annotation('textbox',...
    pos1 + [0.03 0 0 0],...
    'String','a',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','XAxisLocation','top',...
    'box','on','FontSize',fontsize, 'FontName', 'Times New Roman')




ax2 = subplot('Position',pos2)
hold on
plot(ax2, vdpData.time, vdpData.mean_imag,...
    'Color','k','LineWidth', linethickness)
plot(ax2, vdpData.time,...
    vdpData.mean_imag+vdpData.std_imag,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax2, vdpData.time,...
    vdpData.mean_imag-vdpData.std_imag,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
xlabel({'$t$'},'Interpreter','latex')
ylabel({'Im$(\lambda_1)$'},'Interpreter','latex')
xlim([200,380]);
ylim([0.91,1.09]);
xticklabels([]);
ann = annotation('textbox',...
    pos2 + [0.03 0 0 0],...
    'String','b',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')






ax3 = subplot('Position',pos3)
hold on
plot(ax3, vdpData.time, vdpData.mean_ACF1,...
    'Color','k','LineWidth', linethickness)
plot(ax3, vdpData.time,...
    vdpData.mean_ACF1+vdpData.std_ACF1,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax3, vdpData.time,...
    vdpData.mean_ACF1-vdpData.std_ACF1,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
ylabel({'ACF1'},'Interpreter','latex')
xlim([200,380]);
ylim([0.43,0.57]);
xticklabels([]);
ann = annotation('textbox',...
    pos3 + [0.03 0 0 0],...
    'String','c',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')




ax4 = subplot('Position',pos4)
hold on
plot(ax4, vdpData.time, vdpData.mean_DFA,...
    'Color','k','LineWidth', linethickness)
plot(ax4, vdpData.time,...
    vdpData.mean_DFA+vdpData.std_DFA,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
plot(ax4, vdpData.time,...
    vdpData.mean_DFA-vdpData.std_DFA,...
    'Color','k','LineWidth', linethickness,'LineStyle', '--')
%yticks([0.6 0.8 1 1.2 1.4])
xlabel({'$t$'},'Interpreter','latex')
ylabel({'DFA'},'Interpreter','latex')
xlim([200,380]);
ylim([0,0.45]);
%xticklabels([]);
ann = annotation('textbox',...
    pos4 + [0.03 0 0 0],...
    'String','d',...
    'FontSize', 30',...
    'LineStyle', 'none',...
    'FitBoxToText', 'off',...
    'FontName', 'Times New Roman');
set(gca,'YGrid','on','XGrid','on','box','on',...
    'FontSize',fontsize, 'FontName', 'Times New Roman')

%% PS ylim([-0.7, 3.1]);

